version: "3.9"
services:
  iqfeed:
    image: kvokka/iqfeed:a40cf51d535764fbd7428d8dc2e7cf994baf4f36
    container_name: iqfeed
    ports:
      - "5009:5009"
      - "9100:9100"
      - "9200:9200"
      - "9300:9300"
      - "9400:9400"
      - "8088:8080"
      - "5901:5900"
    volumes:
      - ./logs/iqfeed:/root/DTN/IQFeed
      - ./logs/distdnnd:/var/log/distdnnd
    healthcheck:
      test: ["CMD", "python3", "/root/is_iqfeed_running.py"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 1m
    env_file:
      - .env

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: autoheal
